basePath: /
definitions:
  github_com_nico-hondo_internal_dto.ChangePasswordRequest:
    properties:
      new_password:
        minLength: 6
        type: string
      old_password:
        type: string
    required:
    - new_password
    - old_password
    type: object
  github_com_nico-hondo_internal_dto.ChangeProfileUser:
    properties:
      avatar:
        type: string
      bio:
        type: string
      job:
        type: string
      loc:
        type: string
      nama:
        type: string
      workplace:
        type: string
    type: object
  github_com_nico-hondo_internal_dto.ErrorResponse:
    properties:
      data: {}
      msg:
        type: string
      success:
        type: boolean
    type: object
  github_com_nico-hondo_internal_dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  github_com_nico-hondo_internal_dto.NewTestimoni:
    properties:
      comment:
        type: string
      user_id:
        type: integer
    type: object
  github_com_nico-hondo_internal_dto.RegisterRequest:
    properties:
      email:
        type: string
      nama:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - nama
    - password
    type: object
  github_com_nico-hondo_internal_dto.Response:
    properties:
      data: {}
      msg:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8000
info:
  contact: {}
  description: Completed Eventhub backend during Koda Bootcamp
  title: Koda B9 Backend
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Login Acc from body
      parameters:
      - description: body to login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_nico-hondo_internal_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      summary: Login an Account
      tags:
      - Auth
  /auth/change-password:
    patch:
      consumes:
      - application/json
      description: Change password for logged-in user
      parameters:
      - description: Data Password Baru
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_nico-hondo_internal_dto.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
      security:
      - BearerToken: []
      summary: Change Password User
      tags:
      - Auth
  /auth/change-profile:
    patch:
      consumes:
      - multipart/form-data
      description: Update user profile details using Form Data
      parameters:
      - description: Profile Data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_nico-hondo_internal_dto.ChangeProfileUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
      security:
      - BearerToken: []
      summary: Change Profile User
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Regist Acc from body
      parameters:
      - description: body to register
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_nico-hondo_internal_dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      summary: Register an Account
      tags:
      - Auth
  /community:
    get:
      consumes:
      - application/json
      description: Get list of communities with optional query filter parameters
      parameters:
      - in: query
        name: category
        type: string
      - description: '''upcoming'', ''popular'', ''almost_full'', ''recently_added'''
        in: query
        name: is_joined
        type: string
      - in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      summary: Get list of communities
      tags:
      - Communities
  /community/{id}:
    get:
      consumes:
      - application/json
      description: Get detailed information of a specific community by its ID
      parameters:
      - description: Community ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      summary: Get community detail by ID
      tags:
      - Communities
  /community/popular:
    get:
      consumes:
      - application/json
      description: Retrieve a list of popular communities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      summary: Get list of popular communities
      tags:
      - Communities
  /events:
    get:
      consumes:
      - application/json
      description: Get list of events with optional filter parameters
      parameters:
      - in: query
        name: category
        type: string
      - in: query
        name: location
        type: string
      - in: query
        name: search
        type: string
      - description: '''upcoming'', ''popular'', ''almost_full'', ''recently_added'''
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      summary: Get list of events
      tags:
      - Events
  /events/{id}:
    get:
      consumes:
      - application/json
      description: Get detailed information of a specific event by its ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      summary: Get event detail by ID
      tags:
      - Events
    post:
      consumes:
      - application/json
      description: Join or leave an event by event ID (requires authentication)
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      security:
      - BearerToken: []
      summary: Join or unjoin an event
      tags:
      - Events
  /events/myevents:
    get:
      consumes:
      - application/json
      description: Get list of events joined by the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      security:
      - BearerToken: []
      summary: Get user's joined events
      tags:
      - Events
  /events/upcoming:
    get:
      consumes:
      - application/json
      description: Retrieve a list of upcoming events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      summary: Get upcoming events
      tags:
      - Events
  /my-notification:
    get:
      description: Get Notif Data from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      security:
      - BearerToken: []
      summary: Get All Notif Data
      tags:
      - notif
  /testimony:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all user testimonies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      summary: Get all testimonies
      tags:
      - Testimonies
  /testimony/create:
    post:
      consumes:
      - application/json
      description: Submit a new user testimony (requires authentication)
      parameters:
      - description: Testimony Payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_nico-hondo_internal_dto.NewTestimoni'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nico-hondo_internal_dto.ErrorResponse'
      security:
      - BearerToken: []
      summary: Create a new testimony
      tags:
      - Testimonies
securityDefinitions:
  BearerToken:
    description: Bearer Token used as identity for accessing backend
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
